Question 1:

In [14]:
import numpy as np
a=np.arange(2,50,3)
a

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

Question 2:

In [38]:
arr1 = np.array([0, 6, 2, 3, 4])
arr2 = np.array([5, 1, 7, 8, 9])
arr=np.concatenate((arr1,arr2))
print(arr)
print(np.sort(arr))


[0 6 2 3 4 5 1 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


Question 3:

In [40]:
a= np.array([[0, 1], [1, 0]])
size = a.shape
print(size)

(2, 2)


Question 4:

In [44]:
arr1=np.array([0,1,2,3,4,5])
arr2=np.reshape(arr1,(2,3))
print(arr2)

[[0 1 2]
 [3 4 5]]


Question 5:

In [45]:
arr1=np.arange(15).reshape(5,3)
arr2=np.arange(5).reshape(5,1)
print(arr1)
print(arr2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[0]
 [1]
 [2]
 [3]
 [4]]



Question 6:

In [55]:
#unique count
list = [1, 1, 2, 2, 3]
a_set = set(a_list)
Unique = len(a_set)
print(list)
print(Unique)

[1, 1, 2, 2, 3]
3


In [60]:
#unique values
def unique(list1): 
    x = np.array(list1) 
    print(np.unique(x))
list1 = [10, 20, 10, 30, 40, 40,10,78] 
unique(list1)

[10 20 30 40 78]
